# Generated by Django 4.1 on 2022-12-20 19:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reviews", "0002_review_critic_review_movie_review_review_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="review",
            name="stars",
            field=models.PositiveIntegerField(
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(5),
                ]
            ),
        ),
    ]
